/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.view;
import com.mycompany.classes.Marca;
import com.mycompany.dao.MarcaDAO;

import java.sql.PreparedStatement;

import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Gabriel Miranda
 */
public class IFCadastros extends javax.swing.JPanel {



    public void CadastrarMarca(){
        try{
            MarcaDAO marcaDAO = new MarcaDAO();
            Marca marca = new Marca();

            marca.setDescMarca(TextField_DescMarca.getText().trim());

            if(marcaDAO.validaMarca(marca.getDescMarca())){
                showMessageDialog(this, "Marca já cadastrada ou em branco.");
                return;
            }

            new MarcaDAO().NovaMarca(marca);



            showMessageDialog(this, "Produto cadastrado.");
        }catch(Exception e){
            showMessageDialog(this, e.getMessage());
        }
    }
    
    /**
     * Creates new form IFMarca
     */
    public IFCadastros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IF_Marca = new javax.swing.JInternalFrame();
        TabPane_Cadastrar = new javax.swing.JTabbedPane();
        Painel_NovoProduto = new javax.swing.JPanel();
        Label_DescProd = new javax.swing.JLabel();
        TextField_DescProd = new javax.swing.JTextField();
        ComboBox_Marcas = new javax.swing.JComboBox<>();
        ComboBox_UnidadeMedida = new javax.swing.JComboBox<>();
        Botao_CadastrarProduto = new javax.swing.JButton();
        Botao_CancelarProduto = new javax.swing.JButton();
        Painel_NovaMarca = new javax.swing.JPanel();
        Label_DescMarca = new javax.swing.JLabel();
        TextField_DescMarca = new javax.swing.JTextField();
        Button_CadastrarMarca = new javax.swing.JButton();
        Button_Cancelar = new javax.swing.JButton();
        Painel_NovaUnidadeMedida = new javax.swing.JPanel();
        Label_DescUnidadeMedida = new javax.swing.JLabel();
        TextField_DescUnidadeMedida = new javax.swing.JTextField();
        Button_CancelarUnidadeMedida = new javax.swing.JButton();
        Button_CadastrarUnidadeMedida = new javax.swing.JButton();

        IF_Marca.setVisible(true);

        Painel_NovoProduto.setName(""); // NOI18N

        Label_DescProd.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Label_DescProd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_DescProd.setText("Descrição:");

        ComboBox_Marcas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Marcas" }));

        ComboBox_UnidadeMedida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unidades de Medida" }));

        Botao_CadastrarProduto.setText("Cadastrar");

        Botao_CancelarProduto.setText("Cancelar");
        Botao_CancelarProduto.setPreferredSize(new java.awt.Dimension(83, 25));

        javax.swing.GroupLayout Painel_NovoProdutoLayout = new javax.swing.GroupLayout(Painel_NovoProduto);
        Painel_NovoProduto.setLayout(Painel_NovoProdutoLayout);
        Painel_NovoProdutoLayout.setHorizontalGroup(
            Painel_NovoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_NovoProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_DescProd, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_NovoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_NovoProdutoLayout.createSequentialGroup()
                        .addComponent(ComboBox_UnidadeMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ComboBox_Marcas, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TextField_DescProd, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE))
                .addGap(64, 64, 64))
            .addGroup(Painel_NovoProdutoLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(Botao_CadastrarProduto)
                .addGap(35, 35, 35)
                .addComponent(Botao_CancelarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Painel_NovoProdutoLayout.setVerticalGroup(
            Painel_NovoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_NovoProdutoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(Painel_NovoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_DescProd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_DescProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Painel_NovoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBox_UnidadeMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBox_Marcas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(Painel_NovoProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Botao_CadastrarProduto)
                    .addComponent(Botao_CancelarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        TabPane_Cadastrar.addTab("Novo Produto", Painel_NovoProduto);

        Label_DescMarca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Label_DescMarca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_DescMarca.setText("Descrição:");
        Label_DescMarca.setToolTipText("");

        TextField_DescMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_DescMarcaActionPerformed(evt);
            }
        });

        Button_CadastrarMarca.setText("Cadastrar");
        Button_CadastrarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CadastrarMarcaActionPerformed(evt);
            }
        });

        Button_Cancelar.setText("Cancelar");
        Button_Cancelar.setPreferredSize(new java.awt.Dimension(83, 25));
        Button_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Painel_NovaMarcaLayout = new javax.swing.GroupLayout(Painel_NovaMarca);
        Painel_NovaMarca.setLayout(Painel_NovaMarcaLayout);
        Painel_NovaMarcaLayout.setHorizontalGroup(
            Painel_NovaMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_NovaMarcaLayout.createSequentialGroup()
                .addGroup(Painel_NovaMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_NovaMarcaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Label_DescMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextField_DescMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Painel_NovaMarcaLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(Button_CadastrarMarca)
                        .addGap(35, 35, 35)
                        .addComponent(Button_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Painel_NovaMarcaLayout.setVerticalGroup(
            Painel_NovaMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_NovaMarcaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Painel_NovaMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_DescMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_DescMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(Painel_NovaMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_CadastrarMarca)
                    .addComponent(Button_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        TabPane_Cadastrar.addTab("Nova Marca", Painel_NovaMarca);

        Label_DescUnidadeMedida.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Label_DescUnidadeMedida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_DescUnidadeMedida.setText("Descrição:");

        Button_CancelarUnidadeMedida.setText("Cancelar");
        Button_CancelarUnidadeMedida.setPreferredSize(new java.awt.Dimension(83, 25));

        Button_CadastrarUnidadeMedida.setText("Cadastrar");

        javax.swing.GroupLayout Painel_NovaUnidadeMedidaLayout = new javax.swing.GroupLayout(Painel_NovaUnidadeMedida);
        Painel_NovaUnidadeMedida.setLayout(Painel_NovaUnidadeMedidaLayout);
        Painel_NovaUnidadeMedidaLayout.setHorizontalGroup(
            Painel_NovaUnidadeMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_NovaUnidadeMedidaLayout.createSequentialGroup()
                .addGroup(Painel_NovaUnidadeMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_NovaUnidadeMedidaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Label_DescUnidadeMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextField_DescUnidadeMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Painel_NovaUnidadeMedidaLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(Button_CadastrarUnidadeMedida)
                        .addGap(35, 35, 35)
                        .addComponent(Button_CancelarUnidadeMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        Painel_NovaUnidadeMedidaLayout.setVerticalGroup(
            Painel_NovaUnidadeMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_NovaUnidadeMedidaLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(Painel_NovaUnidadeMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_DescUnidadeMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_DescUnidadeMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(Painel_NovaUnidadeMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_CadastrarUnidadeMedida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_CancelarUnidadeMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        TabPane_Cadastrar.addTab("Nova Unidade de Medida", Painel_NovaUnidadeMedida);

        IF_Marca.getContentPane().add(TabPane_Cadastrar, java.awt.BorderLayout.PAGE_START);
        TabPane_Cadastrar.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IF_Marca)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IF_Marca)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_DescMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_DescMarcaActionPerformed
        
    }//GEN-LAST:event_TextField_DescMarcaActionPerformed

    private void Button_CadastrarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CadastrarMarcaActionPerformed
        if(evt.getSource() == Button_CadastrarMarca){
            CadastrarMarca();
        }
    }//GEN-LAST:event_Button_CadastrarMarcaActionPerformed

    private void Button_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CancelarActionPerformed
        new IFCadastros().setVisible(false);
    }//GEN-LAST:event_Button_CancelarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botao_CadastrarProduto;
    private javax.swing.JButton Botao_CancelarProduto;
    private javax.swing.JButton Button_CadastrarMarca;
    private javax.swing.JButton Button_CadastrarUnidadeMedida;
    private javax.swing.JButton Button_Cancelar;
    private javax.swing.JButton Button_CancelarUnidadeMedida;
    private javax.swing.JComboBox<String> ComboBox_Marcas;
    private javax.swing.JComboBox<String> ComboBox_UnidadeMedida;
    private javax.swing.JInternalFrame IF_Marca;
    private javax.swing.JLabel Label_DescMarca;
    private javax.swing.JLabel Label_DescProd;
    private javax.swing.JLabel Label_DescUnidadeMedida;
    private javax.swing.JPanel Painel_NovaMarca;
    private javax.swing.JPanel Painel_NovaUnidadeMedida;
    private javax.swing.JPanel Painel_NovoProduto;
    private javax.swing.JTabbedPane TabPane_Cadastrar;
    private javax.swing.JTextField TextField_DescMarca;
    private javax.swing.JTextField TextField_DescProd;
    private javax.swing.JTextField TextField_DescUnidadeMedida;
    // End of variables declaration//GEN-END:variables

}
